"""Kunden und Instrumente archivierbar

Revision ID: 22b61f44d096
Revises: 30411833d9d0
Create Date: 2026-09-27 22:51:01.998426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22b61f44d096'
down_revision: Union[str, Sequence[str], None] = '30411833d9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument', sa.Column('archiviert_am', sa.DateTime(timezone=True), nullable=True))
    op.add_column('kunde', sa.Column('archiviert_am', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Fortlaufender Zähler für Kundennummern neuer Kunden (z. B. K-00001)
    op.execute("CREATE SEQUENCE kundennummer_seq")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP SEQUENCE kundennummer_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kunde', 'archiviert_am')
    op.drop_column('instrument', 'archiviert_am')
    # ### end Alembic commands ###
