"""Wochenstunden nur ein offener Eintrag

Revision ID: f42a0bd2b524
Revises: 29fba7051bcf
Create Date: 2026-09-28 18:04:38.736760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42a0bd2b524'
down_revision: Union[str, Sequence[str], None] = '29fba7051bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_mitarbeiter_arbeitszeit_aktuell', 'mitarbeiter_arbeitszeit', ['mitarbeiter_id'], unique=True, postgresql_where=sa.text('gueltig_bis IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_mitarbeiter_arbeitszeit_aktuell', table_name='mitarbeiter_arbeitszeit', postgresql_where=sa.text('gueltig_bis IS NULL'))
    # ### end Alembic commands ###
