"""Statusfarben und Symbole nach Design-System

Revision ID: e4f5bcfdd9ee
Revises: a87059afdfe2
Create Date: 2026-09-27 20:45:26.694286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f5bcfdd9ee'
down_revision: Union[str, Sequence[str], None] = 'a87059afdfe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

DESIGN = [
    ("angenommen", "#8A8378", "○"),
    ("in_bearbeitung", "#4A6FA5", "◐"),
    ("wartet_auf_ersatzteil", "#C97F2E", "⏸"),
    ("qualitaetspruefung", "#6B5B8A", "◑"),
    ("fertig", "#4B6B4F", "✓"),
    # In 9.6 nicht festgelegt – vorläufig dunkles Neutral, bitte im Datenmodell ergänzen
    ("abgeholt", "#5E554C", "●"),
]
VORHER = [
    ("angenommen", "#757575"), ("in_bearbeitung", "#1565C0"), ("wartet_auf_ersatzteil", "#EF6C00"),
    ("qualitaetspruefung", "#6A1B9A"), ("fertig", "#2E7D32"), ("abgeholt", "#37474F"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auftragsstatus', sa.Column('symbol', sa.String(length=4), server_default='○', nullable=False))
    # ### end Alembic commands ###

    # Farben und Symbole nach Design-System (Datenmodell 9.6)
    for schluessel, farbe, symbol in DESIGN:
        op.execute(sa.text("UPDATE auftragsstatus SET farbe = :f, symbol = :s WHERE schluessel = :k")
                   .bindparams(f=farbe, s=symbol, k=schluessel))


def downgrade() -> None:
    """Downgrade schema."""
    for schluessel, farbe in VORHER:
        op.execute(sa.text("UPDATE auftragsstatus SET farbe = :f WHERE schluessel = :k")
                   .bindparams(f=farbe, k=schluessel))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auftragsstatus', 'symbol')
    # ### end Alembic commands ###
