"""Externe Kundennummer

Revision ID: fb55558b75f2
Revises: a94a43b1f3e1
Create Date: 2026-09-28 20:14:06.559473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb55558b75f2'
down_revision: Union[str, Sequence[str], None] = 'a94a43b1f3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kunde', sa.Column('externe_kundennummer', sa.String(length=50), nullable=True))
    op.create_unique_constraint(op.f('uq_kunde_externe_kundennummer'), 'kunde', ['externe_kundennummer'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_kunde_externe_kundennummer'), 'kunde', type_='unique')
    op.drop_column('kunde', 'externe_kundennummer')
    # ### end Alembic commands ###
