"""Schaetzungs-Log erweitern, Auftragsnummern

Revision ID: 77294ab78d7a
Revises: f43a19ed6e10
Create Date: 2026-09-27 19:09:44.515768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77294ab78d7a'
down_revision: Union[str, Sequence[str], None] = 'f43a19ed6e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schaetzungs_log', sa.Column('geschaetzte_stunden', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('schaetzungs_log', sa.Column('geschaetzte_kosten', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('schaetzungs_log', sa.Column('korrigiert_von_mitarbeiter_id', sa.UUID(), nullable=True))
    op.add_column('schaetzungs_log', sa.Column('grund', sa.Text(), nullable=True))
    op.alter_column('schaetzungs_log', 'geschaetztes_datum',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(op.f('fk_schaetzungs_log_korrigiert_von_mitarbeiter_id_mitarbeiter'), 'schaetzungs_log', 'mitarbeiter', ['korrigiert_von_mitarbeiter_id'], ['id'])
    # ### end Alembic commands ###

    # Von Hand ergänzt: Prüfregeln an bestehender Tabelle erkennt Autogenerate nicht
    op.create_check_constraint(
        op.f("ck_schaetzungs_log_korrektur_mit_mitarbeiter_und_grund"), "schaetzungs_log",
        "methode <> 'manuelle_korrektur' OR "
        "(korrigiert_von_mitarbeiter_id IS NOT NULL AND grund IS NOT NULL AND btrim(grund) <> '')",
    )
    op.create_check_constraint(
        op.f("ck_schaetzungs_log_stunden_nicht_negativ"), "schaetzungs_log",
        "geschaetzte_stunden IS NULL OR geschaetzte_stunden >= 0",
    )
    op.create_check_constraint(
        op.f("ck_schaetzungs_log_kosten_nicht_negativ"), "schaetzungs_log",
        "geschaetzte_kosten IS NULL OR geschaetzte_kosten >= 0",
    )
    # Fortlaufender Zähler für lesbare Auftragsnummern (z. B. 2026-00001)
    op.execute("CREATE SEQUENCE auftragsnummer_seq")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP SEQUENCE auftragsnummer_seq")
    for name in ("kosten_nicht_negativ", "stunden_nicht_negativ", "korrektur_mit_mitarbeiter_und_grund"):
        op.drop_constraint(op.f(f"ck_schaetzungs_log_{name}"), "schaetzungs_log", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_schaetzungs_log_korrigiert_von_mitarbeiter_id_mitarbeiter'), 'schaetzungs_log', type_='foreignkey')
    op.alter_column('schaetzungs_log', 'geschaetztes_datum',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('schaetzungs_log', 'grund')
    op.drop_column('schaetzungs_log', 'korrigiert_von_mitarbeiter_id')
    op.drop_column('schaetzungs_log', 'geschaetzte_kosten')
    op.drop_column('schaetzungs_log', 'geschaetzte_stunden')
    # ### end Alembic commands ###
