"""Unterbrechung bei pausierenden Status

Revision ID: 30411833d9d0
Revises: e4f5bcfdd9ee
Create Date: 2026-09-27 21:37:47.286586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30411833d9d0'
down_revision: Union[str, Sequence[str], None] = 'e4f5bcfdd9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auftragsstatus', sa.Column('unterbrechungsgrund', sa.String(length=200), nullable=True))
    op.create_index('uq_unterbrechung_offen_je_auftrag', 'unterbrechung', ['auftrag_id'], unique=True, postgresql_where=sa.text('bis_datum IS NULL'))
    # ### end Alembic commands ###

    # "Wartet auf Ersatzteil" pausiert den Auftrag
    op.execute("UPDATE auftragsstatus SET unterbrechungsgrund = 'Ersatzteil bestellt' "
               "WHERE schluessel = 'wartet_auf_ersatzteil'")
    # Nachtrag: Aufträge, die bereits in einem pausierenden Status stehen, bekommen eine
    # offene Unterbrechung ab ihrem letzten Wechsel in diesen Status
    op.execute("""
        INSERT INTO unterbrechung (auftrag_id, grund, von_datum)
        SELECT a.id, s.unterbrechungsgrund,
               COALESCE((SELECT max(v.geaendert_am) FROM auftrag_statusverlauf v
                         WHERE v.auftrag_id = a.id AND v.status_id = s.id), clock_timestamp())
        FROM auftrag a
        JOIN auftragsstatus s ON s.id = a.status_aktuell_id
        WHERE s.unterbrechungsgrund IS NOT NULL
          AND NOT EXISTS (SELECT 1 FROM unterbrechung u WHERE u.auftrag_id = a.id AND u.bis_datum IS NULL)
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_unterbrechung_offen_je_auftrag', table_name='unterbrechung', postgresql_where=sa.text('bis_datum IS NULL'))
    op.drop_column('auftragsstatus', 'unterbrechungsgrund')
    # ### end Alembic commands ###
