"""Abwesenheit Notiz und Werkstatt-Einstellungen

Revision ID: 910c0f03c1d8
Revises: c3d81f0a7b42
Create Date: 2026-10-02 18:29:23.427105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910c0f03c1d8'
down_revision: Union[str, Sequence[str], None] = 'c3d81f0a7b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('einstellung',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('schluessel', sa.String(length=50), nullable=False),
    sa.Column('wert', sa.String(length=200), nullable=False),
    sa.Column('geaendert_von_mitarbeiter_id', sa.UUID(), nullable=True),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['geaendert_von_mitarbeiter_id'], ['mitarbeiter.id'], name=op.f('fk_einstellung_geaendert_von_mitarbeiter_id_mitarbeiter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_einstellung')),
    sa.UniqueConstraint('schluessel', name=op.f('uq_einstellung_schluessel'))
    )
    op.add_column('abwesenheit', sa.Column('notiz', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # Supabase-REST-API für die neue Tabelle sperren (siehe erste Migration)
    op.execute('ALTER TABLE "einstellung" ENABLE ROW LEVEL SECURITY')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abwesenheit', 'notiz')
    op.drop_table('einstellung')
    # ### end Alembic commands ###
