"""Grundschema anlegen

Revision ID: e7c6b2484647
Revises: 
Create Date: 2026-09-27 18:19:39.567820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7c6b2484647'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABELLEN = [
    "kunde", "mitarbeiter", "abwesenheit", "instrumentenklasse", "reparaturart",
    "auftragsstatus", "instrument", "auftrag", "auftrag_statusverlauf", "unterbrechung",
    "schaetzungs_log", "arbeitszeiterfassung", "mitarbeiter_arbeitszeit",
    "mitarbeiter_qualifikation", "arbeitszeit_anpassung", "system_ereignis_log",
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auftragsstatus',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('schluessel', sa.String(length=50), nullable=False),
    sa.Column('bezeichnung', sa.String(length=100), nullable=False),
    sa.Column('reihenfolge', sa.SmallInteger(), nullable=False),
    sa.Column('farbe', sa.String(length=7), nullable=False),
    sa.Column('erfordert_zeiterfassung', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ist_abgeschlossen', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('aktiv', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auftragsstatus')),
    sa.UniqueConstraint('bezeichnung', name=op.f('uq_auftragsstatus_bezeichnung')),
    sa.UniqueConstraint('schluessel', name=op.f('uq_auftragsstatus_schluessel'))
    )
    op.create_table('instrumentenklasse',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bezeichnung', sa.String(length=100), nullable=False),
    sa.Column('oberkategorie', sa.String(length=100), nullable=False),
    sa.Column('aktiv', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instrumentenklasse')),
    sa.UniqueConstraint('bezeichnung', name=op.f('uq_instrumentenklasse_bezeichnung'))
    )
    op.create_table('kunde',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kundennummer', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kunde')),
    sa.UniqueConstraint('kundennummer', name=op.f('uq_kunde_kundennummer'))
    )
    op.create_table('mitarbeiter',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rolle', sa.String(length=100), nullable=True),
    sa.Column('systemrolle', sa.Enum('mitarbeiter', 'werkstattleiter', 'admin', name='systemrolle'), server_default='mitarbeiter', nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('passwort_hash', sa.String(length=255), nullable=False),
    sa.Column('aktiv', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deaktiviert_am', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(aktiv AND deaktiviert_am IS NULL) OR (NOT aktiv AND deaktiviert_am IS NOT NULL)', name=op.f('ck_mitarbeiter_deaktiviert_am_passt_zu_aktiv')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mitarbeiter')),
    sa.UniqueConstraint('email', name=op.f('uq_mitarbeiter_email'))
    )
    op.create_table('reparaturart',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bezeichnung', sa.String(length=150), nullable=False),
    sa.Column('standard_komplexitaet', sa.SmallInteger(), nullable=False),
    sa.Column('aktiv', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('standard_komplexitaet BETWEEN 1 AND 5', name=op.f('ck_reparaturart_komplexitaet_1_bis_5')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reparaturart')),
    sa.UniqueConstraint('bezeichnung', name=op.f('uq_reparaturart_bezeichnung'))
    )
    op.create_table('abwesenheit',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mitarbeiter_id', sa.UUID(), nullable=True),
    sa.Column('von_datum', sa.Date(), nullable=False),
    sa.Column('bis_datum', sa.Date(), nullable=False),
    sa.Column('typ', sa.Enum('urlaub', 'krankheit', 'feiertag', 'betriebsschliessung', 'schulung', 'reduzierte_stunden', name='abwesenheitstyp'), nullable=False),
    sa.Column('reduzierte_stunden', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.CheckConstraint('bis_datum >= von_datum', name=op.f('ck_abwesenheit_zeitraum_gueltig')),
    sa.CheckConstraint('reduzierte_stunden IS NULL OR reduzierte_stunden >= 0', name=op.f('ck_abwesenheit_reduzierte_stunden_positiv')),
    sa.ForeignKeyConstraint(['mitarbeiter_id'], ['mitarbeiter.id'], name=op.f('fk_abwesenheit_mitarbeiter_id_mitarbeiter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abwesenheit'))
    )
    op.create_index(op.f('ix_abwesenheit_mitarbeiter_id'), 'abwesenheit', ['mitarbeiter_id'], unique=False)
    op.create_table('arbeitszeit_anpassung',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mitarbeiter_id', sa.UUID(), nullable=False),
    sa.Column('woche_start_datum', sa.Date(), nullable=False),
    sa.Column('anpassung_stunden', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('grund', sa.String(length=200), nullable=True),
    sa.Column('erfasst_von_mitarbeiter_id', sa.UUID(), nullable=True),
    sa.Column('erfasst_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('EXTRACT(ISODOW FROM woche_start_datum) = 1', name=op.f('ck_arbeitszeit_anpassung_woche_beginnt_montags')),
    sa.ForeignKeyConstraint(['erfasst_von_mitarbeiter_id'], ['mitarbeiter.id'], name=op.f('fk_arbeitszeit_anpassung_erfasst_von_mitarbeiter_id_mitarbeiter')),
    sa.ForeignKeyConstraint(['mitarbeiter_id'], ['mitarbeiter.id'], name=op.f('fk_arbeitszeit_anpassung_mitarbeiter_id_mitarbeiter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_arbeitszeit_anpassung'))
    )
    op.create_index(op.f('ix_arbeitszeit_anpassung_mitarbeiter_id'), 'arbeitszeit_anpassung', ['mitarbeiter_id'], unique=False)
    op.create_table('instrument',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kunde_id', sa.UUID(), nullable=False),
    sa.Column('instrumentenklasse_id', sa.UUID(), nullable=False),
    sa.Column('hersteller', sa.String(length=150), nullable=True),
    sa.Column('typenbezeichnung', sa.String(length=150), nullable=True),
    sa.Column('baujahr', sa.Integer(), nullable=True),
    sa.Column('seriennummer', sa.String(length=100), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instrumentenklasse_id'], ['instrumentenklasse.id'], name=op.f('fk_instrument_instrumentenklasse_id_instrumentenklasse')),
    sa.ForeignKeyConstraint(['kunde_id'], ['kunde.id'], name=op.f('fk_instrument_kunde_id_kunde')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instrument'))
    )
    op.create_index(op.f('ix_instrument_instrumentenklasse_id'), 'instrument', ['instrumentenklasse_id'], unique=False)
    op.create_index(op.f('ix_instrument_kunde_id'), 'instrument', ['kunde_id'], unique=False)
    op.create_table('mitarbeiter_arbeitszeit',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mitarbeiter_id', sa.UUID(), nullable=False),
    sa.Column('wochenstunden', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gueltig_ab', sa.Date(), nullable=False),
    sa.Column('gueltig_bis', sa.Date(), nullable=True),
    sa.Column('geaendert_von_mitarbeiter_id', sa.UUID(), nullable=True),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('gueltig_bis IS NULL OR gueltig_bis >= gueltig_ab', name=op.f('ck_mitarbeiter_arbeitszeit_zeitraum_gueltig')),
    sa.CheckConstraint('wochenstunden >= 0', name=op.f('ck_mitarbeiter_arbeitszeit_wochenstunden_positiv')),
    sa.ForeignKeyConstraint(['geaendert_von_mitarbeiter_id'], ['mitarbeiter.id'], name=op.f('fk_mitarbeiter_arbeitszeit_geaendert_von_mitarbeiter_id_mitarbeiter')),
    sa.ForeignKeyConstraint(['mitarbeiter_id'], ['mitarbeiter.id'], name=op.f('fk_mitarbeiter_arbeitszeit_mitarbeiter_id_mitarbeiter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mitarbeiter_arbeitszeit'))
    )
    op.create_index(op.f('ix_mitarbeiter_arbeitszeit_mitarbeiter_id'), 'mitarbeiter_arbeitszeit', ['mitarbeiter_id'], unique=False)
    op.create_table('mitarbeiter_qualifikation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mitarbeiter_id', sa.UUID(), nullable=False),
    sa.Column('reparaturart_id', sa.UUID(), nullable=True),
    sa.Column('instrumentenklasse_id', sa.UUID(), nullable=True),
    sa.Column('bezeichnung', sa.String(length=200), nullable=False),
    sa.Column('erworben_am', sa.Date(), nullable=True),
    sa.Column('gueltig_bis', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['instrumentenklasse_id'], ['instrumentenklasse.id'], name=op.f('fk_mitarbeiter_qualifikation_instrumentenklasse_id_instrumentenklasse')),
    sa.ForeignKeyConstraint(['mitarbeiter_id'], ['mitarbeiter.id'], name=op.f('fk_mitarbeiter_qualifikation_mitarbeiter_id_mitarbeiter')),
    sa.ForeignKeyConstraint(['reparaturart_id'], ['reparaturart.id'], name=op.f('fk_mitarbeiter_qualifikation_reparaturart_id_reparaturart')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mitarbeiter_qualifikation'))
    )
    op.create_index(op.f('ix_mitarbeiter_qualifikation_mitarbeiter_id'), 'mitarbeiter_qualifikation', ['mitarbeiter_id'], unique=False)
    op.create_table('system_ereignis_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ausgefuehrt_von_mitarbeiter_id', sa.UUID(), nullable=True),
    sa.Column('aktion', sa.String(length=100), nullable=False),
    sa.Column('betroffene_entitaet', sa.String(length=100), nullable=False),
    sa.Column('betroffene_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('zeitpunkt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ausgefuehrt_von_mitarbeiter_id'], ['mitarbeiter.id'], name=op.f('fk_system_ereignis_log_ausgefuehrt_von_mitarbeiter_id_mitarbeiter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_ereignis_log'))
    )
    op.create_index(op.f('ix_system_ereignis_log_ausgefuehrt_von_mitarbeiter_id'), 'system_ereignis_log', ['ausgefuehrt_von_mitarbeiter_id'], unique=False)
    op.create_table('auftrag',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('auftragsnummer', sa.String(length=30), nullable=False),
    sa.Column('zugriffstoken', sa.String(length=64), nullable=False),
    sa.Column('kunde_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('reparaturart_id', sa.UUID(), nullable=False),
    sa.Column('zugewiesener_mitarbeiter_id', sa.UUID(), nullable=True),
    sa.Column('prioritaet', sa.Enum('normal', 'hoch', name='prioritaet'), server_default='normal', nullable=False),
    sa.Column('komplexitaet', sa.SmallInteger(), nullable=False),
    sa.Column('status_aktuell_id', sa.UUID(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geschaetztes_fertigstellungsdatum', sa.Date(), nullable=True),
    sa.Column('geschaetzte_bandbreite_von', sa.Date(), nullable=True),
    sa.Column('geschaetzte_bandbreite_bis', sa.Date(), nullable=True),
    sa.Column('geschaetzte_arbeitsstunden', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('tatsaechliches_fertigstellungsdatum', sa.Date(), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.CheckConstraint('geschaetzte_bandbreite_bis IS NULL OR geschaetzte_bandbreite_von IS NULL OR geschaetzte_bandbreite_bis >= geschaetzte_bandbreite_von', name=op.f('ck_auftrag_bandbreite_gueltig')),
    sa.CheckConstraint('komplexitaet BETWEEN 1 AND 5', name=op.f('ck_auftrag_komplexitaet_1_bis_5')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], name=op.f('fk_auftrag_instrument_id_instrument')),
    sa.ForeignKeyConstraint(['kunde_id'], ['kunde.id'], name=op.f('fk_auftrag_kunde_id_kunde')),
    sa.ForeignKeyConstraint(['reparaturart_id'], ['reparaturart.id'], name=op.f('fk_auftrag_reparaturart_id_reparaturart')),
    sa.ForeignKeyConstraint(['status_aktuell_id'], ['auftragsstatus.id'], name=op.f('fk_auftrag_status_aktuell_id_auftragsstatus')),
    sa.ForeignKeyConstraint(['zugewiesener_mitarbeiter_id'], ['mitarbeiter.id'], name=op.f('fk_auftrag_zugewiesener_mitarbeiter_id_mitarbeiter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auftrag')),
    sa.UniqueConstraint('auftragsnummer', name=op.f('uq_auftrag_auftragsnummer')),
    sa.UniqueConstraint('zugriffstoken', name=op.f('uq_auftrag_zugriffstoken'))
    )
    op.create_index(op.f('ix_auftrag_instrument_id'), 'auftrag', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_auftrag_kunde_id'), 'auftrag', ['kunde_id'], unique=False)
    op.create_index(op.f('ix_auftrag_reparaturart_id'), 'auftrag', ['reparaturart_id'], unique=False)
    op.create_index(op.f('ix_auftrag_status_aktuell_id'), 'auftrag', ['status_aktuell_id'], unique=False)
    op.create_index(op.f('ix_auftrag_zugewiesener_mitarbeiter_id'), 'auftrag', ['zugewiesener_mitarbeiter_id'], unique=False)
    op.create_table('arbeitszeiterfassung',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('auftrag_id', sa.UUID(), nullable=False),
    sa.Column('mitarbeiter_id', sa.UUID(), nullable=False),
    sa.Column('dauer_minuten', sa.Integer(), nullable=False),
    sa.Column('erfasst_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kommentar', sa.Text(), nullable=True),
    sa.CheckConstraint('dauer_minuten > 0', name=op.f('ck_arbeitszeiterfassung_dauer_positiv')),
    sa.ForeignKeyConstraint(['auftrag_id'], ['auftrag.id'], name=op.f('fk_arbeitszeiterfassung_auftrag_id_auftrag')),
    sa.ForeignKeyConstraint(['mitarbeiter_id'], ['mitarbeiter.id'], name=op.f('fk_arbeitszeiterfassung_mitarbeiter_id_mitarbeiter')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_arbeitszeiterfassung'))
    )
    op.create_index(op.f('ix_arbeitszeiterfassung_auftrag_id'), 'arbeitszeiterfassung', ['auftrag_id'], unique=False)
    op.create_index(op.f('ix_arbeitszeiterfassung_mitarbeiter_id'), 'arbeitszeiterfassung', ['mitarbeiter_id'], unique=False)
    op.create_table('auftrag_statusverlauf',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('auftrag_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_von_mitarbeiter_id', sa.UUID(), nullable=True),
    sa.Column('kommentar', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['auftrag_id'], ['auftrag.id'], name=op.f('fk_auftrag_statusverlauf_auftrag_id_auftrag')),
    sa.ForeignKeyConstraint(['geaendert_von_mitarbeiter_id'], ['mitarbeiter.id'], name=op.f('fk_auftrag_statusverlauf_geaendert_von_mitarbeiter_id_mitarbeiter')),
    sa.ForeignKeyConstraint(['status_id'], ['auftragsstatus.id'], name=op.f('fk_auftrag_statusverlauf_status_id_auftragsstatus')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auftrag_statusverlauf'))
    )
    op.create_index(op.f('ix_auftrag_statusverlauf_auftrag_id'), 'auftrag_statusverlauf', ['auftrag_id'], unique=False)
    op.create_index(op.f('ix_auftrag_statusverlauf_geaendert_von_mitarbeiter_id'), 'auftrag_statusverlauf', ['geaendert_von_mitarbeiter_id'], unique=False)
    op.create_index(op.f('ix_auftrag_statusverlauf_status_id'), 'auftrag_statusverlauf', ['status_id'], unique=False)
    op.create_table('schaetzungs_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('auftrag_id', sa.UUID(), nullable=False),
    sa.Column('berechnet_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('methode', sa.String(length=50), nullable=False),
    sa.Column('geschaetztes_datum', sa.Date(), nullable=False),
    sa.Column('eingabefaktoren', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['auftrag_id'], ['auftrag.id'], name=op.f('fk_schaetzungs_log_auftrag_id_auftrag')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schaetzungs_log'))
    )
    op.create_index(op.f('ix_schaetzungs_log_auftrag_id'), 'schaetzungs_log', ['auftrag_id'], unique=False)
    op.create_table('unterbrechung',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('auftrag_id', sa.UUID(), nullable=False),
    sa.Column('grund', sa.String(length=200), nullable=False),
    sa.Column('von_datum', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bis_datum', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('bis_datum IS NULL OR bis_datum >= von_datum', name=op.f('ck_unterbrechung_zeitraum_gueltig')),
    sa.ForeignKeyConstraint(['auftrag_id'], ['auftrag.id'], name=op.f('fk_unterbrechung_auftrag_id_auftrag')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unterbrechung'))
    )
    op.create_index(op.f('ix_unterbrechung_auftrag_id'), 'unterbrechung', ['auftrag_id'], unique=False)
    # ### end Alembic commands ###

    # --- Supabase-Schutz ------------------------------------------------------
    # Supabase stellt Tabellen im Schema "public" automatisch über eine
    # öffentliche REST-API bereit. Row Level Security ohne Freigabe-Regeln
    # sperrt diesen Weg komplett. Unser Backend verbindet sich als Eigentümer
    # der Tabellen und ist davon nicht betroffen.
    for tabelle in TABELLEN:
        op.execute(f'ALTER TABLE "{tabelle}" ENABLE ROW LEVEL SECURITY')
    # Auch Alembics eigene Versionstabelle gehört nicht in die öffentliche API
    op.execute("ALTER TABLE alembic_version ENABLE ROW LEVEL SECURITY")

    # --- Start-Status (später im Adminbereich pflegbar) -----------------------
    status = sa.table(
        "auftragsstatus",
        sa.column("schluessel", sa.String),
        sa.column("bezeichnung", sa.String),
        sa.column("reihenfolge", sa.SmallInteger),
        sa.column("farbe", sa.String),
        sa.column("erfordert_zeiterfassung", sa.Boolean),
        sa.column("ist_abgeschlossen", sa.Boolean),
    )
    op.bulk_insert(status, [
        {"schluessel": "angenommen", "bezeichnung": "Angenommen", "reihenfolge": 10,
         "farbe": "#757575", "erfordert_zeiterfassung": False, "ist_abgeschlossen": False},
        {"schluessel": "in_bearbeitung", "bezeichnung": "In Bearbeitung", "reihenfolge": 20,
         "farbe": "#1565C0", "erfordert_zeiterfassung": False, "ist_abgeschlossen": False},
        {"schluessel": "wartet_auf_ersatzteil", "bezeichnung": "Wartet auf Ersatzteil", "reihenfolge": 30,
         "farbe": "#EF6C00", "erfordert_zeiterfassung": False, "ist_abgeschlossen": False},
        {"schluessel": "qualitaetspruefung", "bezeichnung": "Qualitätsprüfung", "reihenfolge": 40,
         "farbe": "#6A1B9A", "erfordert_zeiterfassung": False, "ist_abgeschlossen": False},
        {"schluessel": "fertig", "bezeichnung": "Fertig", "reihenfolge": 50,
         "farbe": "#2E7D32", "erfordert_zeiterfassung": True, "ist_abgeschlossen": True},
        {"schluessel": "abgeholt", "bezeichnung": "Abgeholt", "reihenfolge": 60,
         "farbe": "#37474F", "erfordert_zeiterfassung": False, "ist_abgeschlossen": True},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unterbrechung_auftrag_id'), table_name='unterbrechung')
    op.drop_table('unterbrechung')
    op.drop_index(op.f('ix_schaetzungs_log_auftrag_id'), table_name='schaetzungs_log')
    op.drop_table('schaetzungs_log')
    op.drop_index(op.f('ix_auftrag_statusverlauf_status_id'), table_name='auftrag_statusverlauf')
    op.drop_index(op.f('ix_auftrag_statusverlauf_geaendert_von_mitarbeiter_id'), table_name='auftrag_statusverlauf')
    op.drop_index(op.f('ix_auftrag_statusverlauf_auftrag_id'), table_name='auftrag_statusverlauf')
    op.drop_table('auftrag_statusverlauf')
    op.drop_index(op.f('ix_arbeitszeiterfassung_mitarbeiter_id'), table_name='arbeitszeiterfassung')
    op.drop_index(op.f('ix_arbeitszeiterfassung_auftrag_id'), table_name='arbeitszeiterfassung')
    op.drop_table('arbeitszeiterfassung')
    op.drop_index(op.f('ix_auftrag_zugewiesener_mitarbeiter_id'), table_name='auftrag')
    op.drop_index(op.f('ix_auftrag_status_aktuell_id'), table_name='auftrag')
    op.drop_index(op.f('ix_auftrag_reparaturart_id'), table_name='auftrag')
    op.drop_index(op.f('ix_auftrag_kunde_id'), table_name='auftrag')
    op.drop_index(op.f('ix_auftrag_instrument_id'), table_name='auftrag')
    op.drop_table('auftrag')
    op.drop_index(op.f('ix_system_ereignis_log_ausgefuehrt_von_mitarbeiter_id'), table_name='system_ereignis_log')
    op.drop_table('system_ereignis_log')
    op.drop_index(op.f('ix_mitarbeiter_qualifikation_mitarbeiter_id'), table_name='mitarbeiter_qualifikation')
    op.drop_table('mitarbeiter_qualifikation')
    op.drop_index(op.f('ix_mitarbeiter_arbeitszeit_mitarbeiter_id'), table_name='mitarbeiter_arbeitszeit')
    op.drop_table('mitarbeiter_arbeitszeit')
    op.drop_index(op.f('ix_instrument_kunde_id'), table_name='instrument')
    op.drop_index(op.f('ix_instrument_instrumentenklasse_id'), table_name='instrument')
    op.drop_table('instrument')
    op.drop_index(op.f('ix_arbeitszeit_anpassung_mitarbeiter_id'), table_name='arbeitszeit_anpassung')
    op.drop_table('arbeitszeit_anpassung')
    op.drop_index(op.f('ix_abwesenheit_mitarbeiter_id'), table_name='abwesenheit')
    op.drop_table('abwesenheit')
    op.drop_table('reparaturart')
    op.drop_table('mitarbeiter')
    op.drop_table('kunde')
    op.drop_table('instrumentenklasse')
    op.drop_table('auftragsstatus')
    # ### end Alembic commands ###

    for enum_name in ("prioritaet", "abwesenheitstyp", "systemrolle"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
