"""Vorgabewerte archivierbar

Revision ID: a94a43b1f3e1
Revises: f42a0bd2b524
Create Date: 2026-09-28 19:29:21.820196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94a43b1f3e1'
down_revision: Union[str, Sequence[str], None] = 'f42a0bd2b524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reparatur_vorgabewert', sa.Column('archiviert_am', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('uq_reparatur_vorgabewert_kombination'), 'reparatur_vorgabewert', type_='unique')
    op.create_index('uq_reparatur_vorgabewert_kombination', 'reparatur_vorgabewert', ['reparaturart_id', 'instrumentenklasse_id'], unique=True, postgresql_nulls_not_distinct=True, postgresql_where=sa.text('archiviert_am IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_reparatur_vorgabewert_kombination', table_name='reparatur_vorgabewert', postgresql_nulls_not_distinct=True, postgresql_where=sa.text('archiviert_am IS NULL'))
    op.create_unique_constraint(op.f('uq_reparatur_vorgabewert_kombination'), 'reparatur_vorgabewert', ['reparaturart_id', 'instrumentenklasse_id'], postgresql_nulls_not_distinct=True)
    op.drop_column('reparatur_vorgabewert', 'archiviert_am')
    # ### end Alembic commands ###
