"""Vorgabewerte und Kostenfelder

Revision ID: f43a19ed6e10
Revises: e7c6b2484647
Create Date: 2026-09-27 18:49:37.193541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43a19ed6e10'
down_revision: Union[str, Sequence[str], None] = 'e7c6b2484647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reparatur_vorgabewert',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reparaturart_id', sa.UUID(), nullable=False),
    sa.Column('instrumentenklasse_id', sa.UUID(), nullable=True),
    sa.Column('vorgabe_stunden', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('vorgabe_kosten', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.Column('geaendert_von_mitarbeiter_id', sa.UUID(), nullable=True),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('vorgabe_kosten >= 0', name=op.f('ck_reparatur_vorgabewert_kosten_nicht_negativ')),
    sa.CheckConstraint('vorgabe_stunden >= 0', name=op.f('ck_reparatur_vorgabewert_stunden_nicht_negativ')),
    sa.ForeignKeyConstraint(['geaendert_von_mitarbeiter_id'], ['mitarbeiter.id'], name=op.f('fk_reparatur_vorgabewert_geaendert_von_mitarbeiter_id_mitarbeiter')),
    sa.ForeignKeyConstraint(['instrumentenklasse_id'], ['instrumentenklasse.id'], name=op.f('fk_reparatur_vorgabewert_instrumentenklasse_id_instrumentenklasse')),
    sa.ForeignKeyConstraint(['reparaturart_id'], ['reparaturart.id'], name=op.f('fk_reparatur_vorgabewert_reparaturart_id_reparaturart')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reparatur_vorgabewert')),
    sa.UniqueConstraint('reparaturart_id', 'instrumentenklasse_id', name='uq_reparatur_vorgabewert_kombination', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_reparatur_vorgabewert_reparaturart_id'), 'reparatur_vorgabewert', ['reparaturart_id'], unique=False)
    op.add_column('auftrag', sa.Column('geschaetzte_kosten', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('auftrag', sa.Column('tatsaechliche_kosten', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###

    # Von Hand ergänzt: Prüfregeln an bestehender Tabelle erkennt Autogenerate nicht
    op.create_check_constraint(
        op.f("ck_auftrag_geschaetzte_kosten_nicht_negativ"), "auftrag",
        "geschaetzte_kosten IS NULL OR geschaetzte_kosten >= 0",
    )
    op.create_check_constraint(
        op.f("ck_auftrag_tatsaechliche_kosten_nicht_negativ"), "auftrag",
        "tatsaechliche_kosten IS NULL OR tatsaechliche_kosten >= 0",
    )
    # Supabase-REST-API für die neue Tabelle sperren (siehe erste Migration)
    op.execute('ALTER TABLE "reparatur_vorgabewert" ENABLE ROW LEVEL SECURITY')


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("ck_auftrag_tatsaechliche_kosten_nicht_negativ"), "auftrag", type_="check")
    op.drop_constraint(op.f("ck_auftrag_geschaetzte_kosten_nicht_negativ"), "auftrag", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auftrag', 'tatsaechliche_kosten')
    op.drop_column('auftrag', 'geschaetzte_kosten')
    op.drop_index(op.f('ix_reparatur_vorgabewert_reparaturart_id'), table_name='reparatur_vorgabewert')
    op.drop_table('reparatur_vorgabewert')
    # ### end Alembic commands ###
